/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as CalendarIndexRouteImport } from './routes/calendar.index'
import { Route as CalendarPublishedRouteImport } from './routes/calendar.published'
import { Route as CalendarPublishingRouteImport } from './routes/calendar.publishing'
import { Route as CalendarScheduleRouteImport } from './routes/calendar.schedule'
import { Route as CharactersIndexRouteImport } from './routes/characters.index'
import { Route as CharactersIdRouteImport } from './routes/characters.$id'
import { Route as CharactersGeneratingRouteImport } from './routes/characters.generating'
import { Route as CharactersPreviewRouteImport } from './routes/characters.preview'
import { Route as CharactersStyleRouteImport } from './routes/characters.style'
import { Route as CharactersUploadRouteImport } from './routes/characters.upload'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as CreateCharacterRouteImport } from './routes/create.character'
import { Route as CreateGeneratingRouteImport } from './routes/create.generating'
import { Route as CreateIdeaRouteImport } from './routes/create.idea'
import { Route as CreateResultRouteImport } from './routes/create.result'
import { Route as CreateScenesRouteImport } from './routes/create.scenes'
import { Route as CreateScriptRouteImport } from './routes/create.script'
import { Route as CreateSettingsRouteImport } from './routes/create.settings'
import { Route as CreateStyleRouteImport } from './routes/create.style'
import { Route as CreateVoiceRouteImport } from './routes/create.voice'
import { Route as EditorIndexRouteImport } from './routes/editor.index'
import { Route as EditorAiRouteImport } from './routes/editor.ai'
import { Route as EditorAudioRouteImport } from './routes/editor.audio'
import { Route as EditorCaptionsRouteImport } from './routes/editor.captions'
import { Route as EditorExportRouteImport } from './routes/editor.export'
import { Route as EditorScenesRouteImport } from './routes/editor.scenes'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects.$id.index'
import { Route as ProjectsIdScenesRouteImport } from './routes/projects.$id.scenes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarPublishedRoute = CalendarPublishedRouteImport.update({
  id: '/calendar/published',
  path: '/calendar/published',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarPublishingRoute = CalendarPublishingRouteImport.update({
  id: '/calendar/publishing',
  path: '/calendar/publishing',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarScheduleRoute = CalendarScheduleRouteImport.update({
  id: '/calendar/schedule',
  path: '/calendar/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersGeneratingRoute = CharactersGeneratingRouteImport.update({
  id: '/characters/generating',
  path: '/characters/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersPreviewRoute = CharactersPreviewRouteImport.update({
  id: '/characters/preview',
  path: '/characters/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersStyleRoute = CharactersStyleRouteImport.update({
  id: '/characters/style',
  path: '/characters/style',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersUploadRoute = CharactersUploadRouteImport.update({
  id: '/characters/upload',
  path: '/characters/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCharacterRoute = CreateCharacterRouteImport.update({
  id: '/create/character',
  path: '/create/character',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateGeneratingRoute = CreateGeneratingRouteImport.update({
  id: '/create/generating',
  path: '/create/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIdeaRoute = CreateIdeaRouteImport.update({
  id: '/create/idea',
  path: '/create/idea',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateResultRoute = CreateResultRouteImport.update({
  id: '/create/result',
  path: '/create/result',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateScenesRoute = CreateScenesRouteImport.update({
  id: '/create/scenes',
  path: '/create/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateScriptRoute = CreateScriptRouteImport.update({
  id: '/create/script',
  path: '/create/script',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateSettingsRoute = CreateSettingsRouteImport.update({
  id: '/create/settings',
  path: '/create/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateStyleRoute = CreateStyleRouteImport.update({
  id: '/create/style',
  path: '/create/style',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateVoiceRoute = CreateVoiceRouteImport.update({
  id: '/create/voice',
  path: '/create/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorAiRoute = EditorAiRouteImport.update({
  id: '/editor/ai',
  path: '/editor/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorAudioRoute = EditorAudioRouteImport.update({
  id: '/editor/audio',
  path: '/editor/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorCaptionsRoute = EditorCaptionsRouteImport.update({
  id: '/editor/captions',
  path: '/editor/captions',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorExportRoute = EditorExportRouteImport.update({
  id: '/editor/export',
  path: '/editor/export',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorScenesRoute = EditorScenesRouteImport.update({
  id: '/editor/scenes',
  path: '/editor/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/projects/$id/',
  path: '/projects/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdScenesRoute = ProjectsIdScenesRouteImport.update({
  id: '/projects/$id/scenes',
  path: '/projects/$id/scenes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/usage': typeof UsageRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/calendar/published': typeof CalendarPublishedRoute
  '/calendar/publishing': typeof CalendarPublishingRoute
  '/calendar/schedule': typeof CalendarScheduleRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters/generating': typeof CharactersGeneratingRoute
  '/characters/preview': typeof CharactersPreviewRoute
  '/characters/style': typeof CharactersStyleRoute
  '/characters/upload': typeof CharactersUploadRoute
  '/create/character': typeof CreateCharacterRoute
  '/create/generating': typeof CreateGeneratingRoute
  '/create/idea': typeof CreateIdeaRoute
  '/create/result': typeof CreateResultRoute
  '/create/scenes': typeof CreateScenesRoute
  '/create/script': typeof CreateScriptRoute
  '/create/settings': typeof CreateSettingsRoute
  '/create/style': typeof CreateStyleRoute
  '/create/voice': typeof CreateVoiceRoute
  '/editor/ai': typeof EditorAiRoute
  '/editor/audio': typeof EditorAudioRoute
  '/editor/captions': typeof EditorCaptionsRoute
  '/editor/export': typeof EditorExportRoute
  '/editor/scenes': typeof EditorScenesRoute
  '/calendar/': typeof CalendarIndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/create/': typeof CreateIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/scenes': typeof ProjectsIdScenesRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/usage': typeof UsageRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/calendar/published': typeof CalendarPublishedRoute
  '/calendar/publishing': typeof CalendarPublishingRoute
  '/calendar/schedule': typeof CalendarScheduleRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters/generating': typeof CharactersGeneratingRoute
  '/characters/preview': typeof CharactersPreviewRoute
  '/characters/style': typeof CharactersStyleRoute
  '/characters/upload': typeof CharactersUploadRoute
  '/create/character': typeof CreateCharacterRoute
  '/create/generating': typeof CreateGeneratingRoute
  '/create/idea': typeof CreateIdeaRoute
  '/create/result': typeof CreateResultRoute
  '/create/scenes': typeof CreateScenesRoute
  '/create/script': typeof CreateScriptRoute
  '/create/settings': typeof CreateSettingsRoute
  '/create/style': typeof CreateStyleRoute
  '/create/voice': typeof CreateVoiceRoute
  '/editor/ai': typeof EditorAiRoute
  '/editor/audio': typeof EditorAudioRoute
  '/editor/captions': typeof EditorCaptionsRoute
  '/editor/export': typeof EditorExportRoute
  '/editor/scenes': typeof EditorScenesRoute
  '/calendar': typeof CalendarIndexRoute
  '/characters': typeof CharactersIndexRoute
  '/create': typeof CreateIndexRoute
  '/editor': typeof EditorIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/scenes': typeof ProjectsIdScenesRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/usage': typeof UsageRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/calendar/published': typeof CalendarPublishedRoute
  '/calendar/publishing': typeof CalendarPublishingRoute
  '/calendar/schedule': typeof CalendarScheduleRoute
  '/characters/$id': typeof CharactersIdRoute
  '/characters/generating': typeof CharactersGeneratingRoute
  '/characters/preview': typeof CharactersPreviewRoute
  '/characters/style': typeof CharactersStyleRoute
  '/characters/upload': typeof CharactersUploadRoute
  '/create/character': typeof CreateCharacterRoute
  '/create/generating': typeof CreateGeneratingRoute
  '/create/idea': typeof CreateIdeaRoute
  '/create/result': typeof CreateResultRoute
  '/create/scenes': typeof CreateScenesRoute
  '/create/script': typeof CreateScriptRoute
  '/create/settings': typeof CreateSettingsRoute
  '/create/style': typeof CreateStyleRoute
  '/create/voice': typeof CreateVoiceRoute
  '/editor/ai': typeof EditorAiRoute
  '/editor/audio': typeof EditorAudioRoute
  '/editor/captions': typeof EditorCaptionsRoute
  '/editor/export': typeof EditorExportRoute
  '/editor/scenes': typeof EditorScenesRoute
  '/calendar/': typeof CalendarIndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/create/': typeof CreateIndexRoute
  '/editor/': typeof EditorIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/scenes': typeof ProjectsIdScenesRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/notifications'
    | '/register'
    | '/usage'
    | '/verify-email'
    | '/welcome'
    | '/calendar/published'
    | '/calendar/publishing'
    | '/calendar/schedule'
    | '/characters/$id'
    | '/characters/generating'
    | '/characters/preview'
    | '/characters/style'
    | '/characters/upload'
    | '/create/character'
    | '/create/generating'
    | '/create/idea'
    | '/create/result'
    | '/create/scenes'
    | '/create/script'
    | '/create/settings'
    | '/create/style'
    | '/create/voice'
    | '/editor/ai'
    | '/editor/audio'
    | '/editor/captions'
    | '/editor/export'
    | '/editor/scenes'
    | '/calendar/'
    | '/characters/'
    | '/create/'
    | '/editor/'
    | '/projects/'
    | '/projects/$id/scenes'
    | '/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/notifications'
    | '/register'
    | '/usage'
    | '/verify-email'
    | '/welcome'
    | '/calendar/published'
    | '/calendar/publishing'
    | '/calendar/schedule'
    | '/characters/$id'
    | '/characters/generating'
    | '/characters/preview'
    | '/characters/style'
    | '/characters/upload'
    | '/create/character'
    | '/create/generating'
    | '/create/idea'
    | '/create/result'
    | '/create/scenes'
    | '/create/script'
    | '/create/settings'
    | '/create/style'
    | '/create/voice'
    | '/editor/ai'
    | '/editor/audio'
    | '/editor/captions'
    | '/editor/export'
    | '/editor/scenes'
    | '/calendar'
    | '/characters'
    | '/create'
    | '/editor'
    | '/projects'
    | '/projects/$id/scenes'
    | '/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/notifications'
    | '/register'
    | '/usage'
    | '/verify-email'
    | '/welcome'
    | '/calendar/published'
    | '/calendar/publishing'
    | '/calendar/schedule'
    | '/characters/$id'
    | '/characters/generating'
    | '/characters/preview'
    | '/characters/style'
    | '/characters/upload'
    | '/create/character'
    | '/create/generating'
    | '/create/idea'
    | '/create/result'
    | '/create/scenes'
    | '/create/script'
    | '/create/settings'
    | '/create/style'
    | '/create/voice'
    | '/editor/ai'
    | '/editor/audio'
    | '/editor/captions'
    | '/editor/export'
    | '/editor/scenes'
    | '/calendar/'
    | '/characters/'
    | '/create/'
    | '/editor/'
    | '/projects/'
    | '/projects/$id/scenes'
    | '/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  UsageRoute: typeof UsageRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WelcomeRoute: typeof WelcomeRoute
  CalendarPublishedRoute: typeof CalendarPublishedRoute
  CalendarPublishingRoute: typeof CalendarPublishingRoute
  CalendarScheduleRoute: typeof CalendarScheduleRoute
  CharactersIdRoute: typeof CharactersIdRoute
  CharactersGeneratingRoute: typeof CharactersGeneratingRoute
  CharactersPreviewRoute: typeof CharactersPreviewRoute
  CharactersStyleRoute: typeof CharactersStyleRoute
  CharactersUploadRoute: typeof CharactersUploadRoute
  CreateCharacterRoute: typeof CreateCharacterRoute
  CreateGeneratingRoute: typeof CreateGeneratingRoute
  CreateIdeaRoute: typeof CreateIdeaRoute
  CreateResultRoute: typeof CreateResultRoute
  CreateScenesRoute: typeof CreateScenesRoute
  CreateScriptRoute: typeof CreateScriptRoute
  CreateSettingsRoute: typeof CreateSettingsRoute
  CreateStyleRoute: typeof CreateStyleRoute
  CreateVoiceRoute: typeof CreateVoiceRoute
  EditorAiRoute: typeof EditorAiRoute
  EditorAudioRoute: typeof EditorAudioRoute
  EditorCaptionsRoute: typeof EditorCaptionsRoute
  EditorExportRoute: typeof EditorExportRoute
  EditorScenesRoute: typeof EditorScenesRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  CreateIndexRoute: typeof CreateIndexRoute
  EditorIndexRoute: typeof EditorIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsIdScenesRoute: typeof ProjectsIdScenesRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/published': {
      id: '/calendar/published'
      path: '/calendar/published'
      fullPath: '/calendar/published'
      preLoaderRoute: typeof CalendarPublishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/publishing': {
      id: '/calendar/publishing'
      path: '/calendar/publishing'
      fullPath: '/calendar/publishing'
      preLoaderRoute: typeof CalendarPublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/schedule': {
      id: '/calendar/schedule'
      path: '/calendar/schedule'
      fullPath: '/calendar/schedule'
      preLoaderRoute: typeof CalendarScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/characters/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/generating': {
      id: '/characters/generating'
      path: '/characters/generating'
      fullPath: '/characters/generating'
      preLoaderRoute: typeof CharactersGeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/preview': {
      id: '/characters/preview'
      path: '/characters/preview'
      fullPath: '/characters/preview'
      preLoaderRoute: typeof CharactersPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/style': {
      id: '/characters/style'
      path: '/characters/style'
      fullPath: '/characters/style'
      preLoaderRoute: typeof CharactersStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/upload': {
      id: '/characters/upload'
      path: '/characters/upload'
      fullPath: '/characters/upload'
      preLoaderRoute: typeof CharactersUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/character': {
      id: '/create/character'
      path: '/create/character'
      fullPath: '/create/character'
      preLoaderRoute: typeof CreateCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/generating': {
      id: '/create/generating'
      path: '/create/generating'
      fullPath: '/create/generating'
      preLoaderRoute: typeof CreateGeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/idea': {
      id: '/create/idea'
      path: '/create/idea'
      fullPath: '/create/idea'
      preLoaderRoute: typeof CreateIdeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/result': {
      id: '/create/result'
      path: '/create/result'
      fullPath: '/create/result'
      preLoaderRoute: typeof CreateResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/scenes': {
      id: '/create/scenes'
      path: '/create/scenes'
      fullPath: '/create/scenes'
      preLoaderRoute: typeof CreateScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/script': {
      id: '/create/script'
      path: '/create/script'
      fullPath: '/create/script'
      preLoaderRoute: typeof CreateScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/settings': {
      id: '/create/settings'
      path: '/create/settings'
      fullPath: '/create/settings'
      preLoaderRoute: typeof CreateSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/style': {
      id: '/create/style'
      path: '/create/style'
      fullPath: '/create/style'
      preLoaderRoute: typeof CreateStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/voice': {
      id: '/create/voice'
      path: '/create/voice'
      fullPath: '/create/voice'
      preLoaderRoute: typeof CreateVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/ai': {
      id: '/editor/ai'
      path: '/editor/ai'
      fullPath: '/editor/ai'
      preLoaderRoute: typeof EditorAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/audio': {
      id: '/editor/audio'
      path: '/editor/audio'
      fullPath: '/editor/audio'
      preLoaderRoute: typeof EditorAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/captions': {
      id: '/editor/captions'
      path: '/editor/captions'
      fullPath: '/editor/captions'
      preLoaderRoute: typeof EditorCaptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/export': {
      id: '/editor/export'
      path: '/editor/export'
      fullPath: '/editor/export'
      preLoaderRoute: typeof EditorExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/scenes': {
      id: '/editor/scenes'
      path: '/editor/scenes'
      fullPath: '/editor/scenes'
      preLoaderRoute: typeof EditorScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/scenes': {
      id: '/projects/$id/scenes'
      path: '/projects/$id/scenes'
      fullPath: '/projects/$id/scenes'
      preLoaderRoute: typeof ProjectsIdScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  UsageRoute: UsageRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WelcomeRoute: WelcomeRoute,
  CalendarPublishedRoute: CalendarPublishedRoute,
  CalendarPublishingRoute: CalendarPublishingRoute,
  CalendarScheduleRoute: CalendarScheduleRoute,
  CharactersIdRoute: CharactersIdRoute,
  CharactersGeneratingRoute: CharactersGeneratingRoute,
  CharactersPreviewRoute: CharactersPreviewRoute,
  CharactersStyleRoute: CharactersStyleRoute,
  CharactersUploadRoute: CharactersUploadRoute,
  CreateCharacterRoute: CreateCharacterRoute,
  CreateGeneratingRoute: CreateGeneratingRoute,
  CreateIdeaRoute: CreateIdeaRoute,
  CreateResultRoute: CreateResultRoute,
  CreateScenesRoute: CreateScenesRoute,
  CreateScriptRoute: CreateScriptRoute,
  CreateSettingsRoute: CreateSettingsRoute,
  CreateStyleRoute: CreateStyleRoute,
  CreateVoiceRoute: CreateVoiceRoute,
  EditorAiRoute: EditorAiRoute,
  EditorAudioRoute: EditorAudioRoute,
  EditorCaptionsRoute: EditorCaptionsRoute,
  EditorExportRoute: EditorExportRoute,
  EditorScenesRoute: EditorScenesRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  CreateIndexRoute: CreateIndexRoute,
  EditorIndexRoute: EditorIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsIdScenesRoute: ProjectsIdScenesRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
