/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as CreateCharacterRouteImport } from './routes/create.character'
import { Route as CreateGeneratingRouteImport } from './routes/create.generating'
import { Route as CreateIdeaRouteImport } from './routes/create.idea'
import { Route as CreateResultRouteImport } from './routes/create.result'
import { Route as CreateScenesRouteImport } from './routes/create.scenes'
import { Route as CreateScriptRouteImport } from './routes/create.script'
import { Route as CreateSettingsRouteImport } from './routes/create.settings'
import { Route as CreateStyleRouteImport } from './routes/create.style'
import { Route as CreateVoiceRouteImport } from './routes/create.voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCharacterRoute = CreateCharacterRouteImport.update({
  id: '/create/character',
  path: '/create/character',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateGeneratingRoute = CreateGeneratingRouteImport.update({
  id: '/create/generating',
  path: '/create/generating',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIdeaRoute = CreateIdeaRouteImport.update({
  id: '/create/idea',
  path: '/create/idea',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateResultRoute = CreateResultRouteImport.update({
  id: '/create/result',
  path: '/create/result',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateScenesRoute = CreateScenesRouteImport.update({
  id: '/create/scenes',
  path: '/create/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateScriptRoute = CreateScriptRouteImport.update({
  id: '/create/script',
  path: '/create/script',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateSettingsRoute = CreateSettingsRouteImport.update({
  id: '/create/settings',
  path: '/create/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateStyleRoute = CreateStyleRouteImport.update({
  id: '/create/style',
  path: '/create/style',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateVoiceRoute = CreateVoiceRouteImport.update({
  id: '/create/voice',
  path: '/create/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/usage': typeof UsageRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/create/character': typeof CreateCharacterRoute
  '/create/generating': typeof CreateGeneratingRoute
  '/create/idea': typeof CreateIdeaRoute
  '/create/result': typeof CreateResultRoute
  '/create/scenes': typeof CreateScenesRoute
  '/create/script': typeof CreateScriptRoute
  '/create/settings': typeof CreateSettingsRoute
  '/create/style': typeof CreateStyleRoute
  '/create/voice': typeof CreateVoiceRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/usage': typeof UsageRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/create/character': typeof CreateCharacterRoute
  '/create/generating': typeof CreateGeneratingRoute
  '/create/idea': typeof CreateIdeaRoute
  '/create/result': typeof CreateResultRoute
  '/create/scenes': typeof CreateScenesRoute
  '/create/script': typeof CreateScriptRoute
  '/create/settings': typeof CreateSettingsRoute
  '/create/style': typeof CreateStyleRoute
  '/create/voice': typeof CreateVoiceRoute
  '/create': typeof CreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/usage': typeof UsageRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/create/character': typeof CreateCharacterRoute
  '/create/generating': typeof CreateGeneratingRoute
  '/create/idea': typeof CreateIdeaRoute
  '/create/result': typeof CreateResultRoute
  '/create/scenes': typeof CreateScenesRoute
  '/create/script': typeof CreateScriptRoute
  '/create/settings': typeof CreateSettingsRoute
  '/create/style': typeof CreateStyleRoute
  '/create/voice': typeof CreateVoiceRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/notifications'
    | '/register'
    | '/usage'
    | '/verify-email'
    | '/welcome'
    | '/create/character'
    | '/create/generating'
    | '/create/idea'
    | '/create/result'
    | '/create/scenes'
    | '/create/script'
    | '/create/settings'
    | '/create/style'
    | '/create/voice'
    | '/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/notifications'
    | '/register'
    | '/usage'
    | '/verify-email'
    | '/welcome'
    | '/create/character'
    | '/create/generating'
    | '/create/idea'
    | '/create/result'
    | '/create/scenes'
    | '/create/script'
    | '/create/settings'
    | '/create/style'
    | '/create/voice'
    | '/create'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/notifications'
    | '/register'
    | '/usage'
    | '/verify-email'
    | '/welcome'
    | '/create/character'
    | '/create/generating'
    | '/create/idea'
    | '/create/result'
    | '/create/scenes'
    | '/create/script'
    | '/create/settings'
    | '/create/style'
    | '/create/voice'
    | '/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  UsageRoute: typeof UsageRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WelcomeRoute: typeof WelcomeRoute
  CreateCharacterRoute: typeof CreateCharacterRoute
  CreateGeneratingRoute: typeof CreateGeneratingRoute
  CreateIdeaRoute: typeof CreateIdeaRoute
  CreateResultRoute: typeof CreateResultRoute
  CreateScenesRoute: typeof CreateScenesRoute
  CreateScriptRoute: typeof CreateScriptRoute
  CreateSettingsRoute: typeof CreateSettingsRoute
  CreateStyleRoute: typeof CreateStyleRoute
  CreateVoiceRoute: typeof CreateVoiceRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/character': {
      id: '/create/character'
      path: '/create/character'
      fullPath: '/create/character'
      preLoaderRoute: typeof CreateCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/generating': {
      id: '/create/generating'
      path: '/create/generating'
      fullPath: '/create/generating'
      preLoaderRoute: typeof CreateGeneratingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/idea': {
      id: '/create/idea'
      path: '/create/idea'
      fullPath: '/create/idea'
      preLoaderRoute: typeof CreateIdeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/result': {
      id: '/create/result'
      path: '/create/result'
      fullPath: '/create/result'
      preLoaderRoute: typeof CreateResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/scenes': {
      id: '/create/scenes'
      path: '/create/scenes'
      fullPath: '/create/scenes'
      preLoaderRoute: typeof CreateScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/script': {
      id: '/create/script'
      path: '/create/script'
      fullPath: '/create/script'
      preLoaderRoute: typeof CreateScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/settings': {
      id: '/create/settings'
      path: '/create/settings'
      fullPath: '/create/settings'
      preLoaderRoute: typeof CreateSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/style': {
      id: '/create/style'
      path: '/create/style'
      fullPath: '/create/style'
      preLoaderRoute: typeof CreateStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/voice': {
      id: '/create/voice'
      path: '/create/voice'
      fullPath: '/create/voice'
      preLoaderRoute: typeof CreateVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  UsageRoute: UsageRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WelcomeRoute: WelcomeRoute,
  CreateCharacterRoute: CreateCharacterRoute,
  CreateGeneratingRoute: CreateGeneratingRoute,
  CreateIdeaRoute: CreateIdeaRoute,
  CreateResultRoute: CreateResultRoute,
  CreateScenesRoute: CreateScenesRoute,
  CreateScriptRoute: CreateScriptRoute,
  CreateSettingsRoute: CreateSettingsRoute,
  CreateStyleRoute: CreateStyleRoute,
  CreateVoiceRoute: CreateVoiceRoute,
  CreateIndexRoute: CreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
